#!/bin/sh

# Called in the beginning of the build.

echo "CLEANUP cleanup"
rm -fv src/Makevars src/mcupgma/clustering_util/Makefile

make -C src -f Makefile clean
make -C src/mcupgma -f Makefile clean

find src -name '*.tar.gz' -delete -print
find src -name '*.o' -delete -print
