/*
  File autogenerated by gengetopt version 2.19.1
  generated with the following command:
  gengetopt -i test_heap.ggo -F test_heap.cmdline 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "getopt.h"

#include "test_heap.cmdline.h"

const char *gengetopt_args_info_purpose = "";

const char *gengetopt_args_info_usage = "Usage: test_heap [OPTIONS]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_help[] = {
  "  -h, --help                  Print help and exit",
  "  -V, --version               Print version and exit",
  "  -s, --rand-seed=INT         random number generator seed",
  "  -b, --break-at=INT          iteration at which to break and dump",
  "  -n, --init-num-numbers=INT  size of initial population  (default=`1000')",
  "  -r, --range=INT             upper bound on the initial random numbers  \n                                (default=`100')",
  "  -p, --reentry=FLOAT         chance of pushing a number after poping the \n                                smallest  (default=`0.5')",
    0
};

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error);


static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->rand_seed_given = 0 ;
  args_info->break_at_given = 0 ;
  args_info->init_num_numbers_given = 0 ;
  args_info->range_given = 0 ;
  args_info->reentry_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  args_info->rand_seed_orig = NULL;
  args_info->break_at_orig = NULL;
  args_info->init_num_numbers_arg = 1000;
  args_info->init_num_numbers_orig = NULL;
  args_info->range_arg = 100;
  args_info->range_orig = NULL;
  args_info->reentry_arg = 0.5;
  args_info->reentry_orig = NULL;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{
  args_info->help_help = gengetopt_args_info_help[0] ;
  args_info->version_help = gengetopt_args_info_help[1] ;
  args_info->rand_seed_help = gengetopt_args_info_help[2] ;
  args_info->break_at_help = gengetopt_args_info_help[3] ;
  args_info->init_num_numbers_help = gengetopt_args_info_help[4] ;
  args_info->range_help = gengetopt_args_info_help[5] ;
  args_info->reentry_help = gengetopt_args_info_help[6] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n", CMDLINE_PARSER_PACKAGE, CMDLINE_PARSER_VERSION);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  printf("\n%s\n\n", gengetopt_args_info_usage);

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n", gengetopt_args_info_description);

  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);
}

static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  
  if (args_info->rand_seed_orig)
    {
      free (args_info->rand_seed_orig); /* free previous argument */
      args_info->rand_seed_orig = 0;
    }
  if (args_info->break_at_orig)
    {
      free (args_info->break_at_orig); /* free previous argument */
      args_info->break_at_orig = 0;
    }
  if (args_info->init_num_numbers_orig)
    {
      free (args_info->init_num_numbers_orig); /* free previous argument */
      args_info->init_num_numbers_orig = 0;
    }
  if (args_info->range_orig)
    {
      free (args_info->range_orig); /* free previous argument */
      args_info->range_orig = 0;
    }
  if (args_info->reentry_orig)
    {
      free (args_info->reentry_orig); /* free previous argument */
      args_info->reentry_orig = 0;
    }
  
  clear_given (args_info);
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  if (args_info->help_given) {
    fprintf(outfile, "%s\n", "help");
  }
  if (args_info->version_given) {
    fprintf(outfile, "%s\n", "version");
  }
  if (args_info->rand_seed_given) {
    if (args_info->rand_seed_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "rand-seed", args_info->rand_seed_orig);
    } else {
      fprintf(outfile, "%s\n", "rand-seed");
    }
  }
  if (args_info->break_at_given) {
    if (args_info->break_at_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "break-at", args_info->break_at_orig);
    } else {
      fprintf(outfile, "%s\n", "break-at");
    }
  }
  if (args_info->init_num_numbers_given) {
    if (args_info->init_num_numbers_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "init-num-numbers", args_info->init_num_numbers_orig);
    } else {
      fprintf(outfile, "%s\n", "init-num-numbers");
    }
  }
  if (args_info->range_given) {
    if (args_info->range_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "range", args_info->range_orig);
    } else {
      fprintf(outfile, "%s\n", "range");
    }
  }
  if (args_info->reentry_given) {
    if (args_info->reentry_orig) {
      fprintf(outfile, "%s=\"%s\"\n", "reentry", args_info->reentry_orig);
    } else {
      fprintf(outfile, "%s\n", "reentry");
    }
  }
  
  fclose (outfile);

  i = EXIT_SUCCESS;
  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}


/* gengetopt_strdup() */
/* strdup.c replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = NULL;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser2 (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;

  result = cmdline_parser_internal (argc, argv, args_info, override, initialize, check_required, NULL);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  return EXIT_SUCCESS;
}

int
cmdline_parser_internal (int argc, char * const *argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = 1;
  optopt = '?';

  while (1)
    {
      int option_index = 0;
      char *stop_char;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "version",	0, NULL, 'V' },
        { "rand-seed",	1, NULL, 's' },
        { "break-at",	1, NULL, 'b' },
        { "init-num-numbers",	1, NULL, 'n' },
        { "range",	1, NULL, 'r' },
        { "reentry",	1, NULL, 'p' },
        { NULL,	0, NULL, 0 }
      };

      stop_char = 0;
      c = getopt_long (argc, argv, "hVs:b:n:r:p:", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 's':	/* random number generator seed.  */
          if (local_args_info.rand_seed_given)
            {
              fprintf (stderr, "%s: `--rand-seed' (`-s') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->rand_seed_given && ! override)
            continue;
          local_args_info.rand_seed_given = 1;
          args_info->rand_seed_given = 1;
          args_info->rand_seed_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->rand_seed_orig)
            free (args_info->rand_seed_orig); /* free previous string */
          args_info->rand_seed_orig = gengetopt_strdup (optarg);
          break;

        case 'b':	/* iteration at which to break and dump.  */
          if (local_args_info.break_at_given)
            {
              fprintf (stderr, "%s: `--break-at' (`-b') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->break_at_given && ! override)
            continue;
          local_args_info.break_at_given = 1;
          args_info->break_at_given = 1;
          args_info->break_at_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->break_at_orig)
            free (args_info->break_at_orig); /* free previous string */
          args_info->break_at_orig = gengetopt_strdup (optarg);
          break;

        case 'n':	/* size of initial population.  */
          if (local_args_info.init_num_numbers_given)
            {
              fprintf (stderr, "%s: `--init-num-numbers' (`-n') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->init_num_numbers_given && ! override)
            continue;
          local_args_info.init_num_numbers_given = 1;
          args_info->init_num_numbers_given = 1;
          args_info->init_num_numbers_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->init_num_numbers_orig)
            free (args_info->init_num_numbers_orig); /* free previous string */
          args_info->init_num_numbers_orig = gengetopt_strdup (optarg);
          break;

        case 'r':	/* upper bound on the initial random numbers.  */
          if (local_args_info.range_given)
            {
              fprintf (stderr, "%s: `--range' (`-r') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->range_given && ! override)
            continue;
          local_args_info.range_given = 1;
          args_info->range_given = 1;
          args_info->range_arg = strtol (optarg, &stop_char, 0);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->range_orig)
            free (args_info->range_orig); /* free previous string */
          args_info->range_orig = gengetopt_strdup (optarg);
          break;

        case 'p':	/* chance of pushing a number after poping the smallest.  */
          if (local_args_info.reentry_given)
            {
              fprintf (stderr, "%s: `--reentry' (`-p') option given more than once%s\n", argv[0], (additional_error ? additional_error : ""));
              goto failure;
            }
          if (args_info->reentry_given && ! override)
            continue;
          local_args_info.reentry_given = 1;
          args_info->reentry_given = 1;
          args_info->reentry_arg = (float)strtod (optarg, &stop_char);
          if (!(stop_char && *stop_char == '\0')) {
            fprintf(stderr, "%s: invalid numeric value: %s\n", argv[0], optarg);
            goto failure;
          }
          if (args_info->reentry_orig)
            free (args_info->reentry_orig); /* free previous string */
          args_info->reentry_orig = gengetopt_strdup (optarg);
          break;


        case 0:	/* Long option with no short option */
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
