/* HashingMergerMain.cmdline.h */

/* File autogenerated by gengetopt version 2.19.1  */

#ifndef HASHINGMERGERMAIN_CMDLINE_H
#define HASHINGMERGERMAIN_CMDLINE_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE "edges2valid_clusters"
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION "1.0"
#endif

struct gengetopt_args_info
{
  const char *help_help; /* Print help and exit help description.  */
  const char *version_help; /* Print version and exit help description.  */
  char * existing_edges_file_arg;	/* Output file for unchanged edges, order maintained.  */
  char * existing_edges_file_orig;	/* Output file for unchanged edges, order maintained original value given at command line.  */
  const char *existing_edges_file_help; /* Output file for unchanged edges, order maintained help description.  */
  char * new_edges_file_arg;	/* Output file for newly born thick edges, not necessarily sorted.  */
  char * new_edges_file_orig;	/* Output file for newly born thick edges, not necessarily sorted original value given at command line.  */
  const char *new_edges_file_help; /* Output file for newly born thick edges, not necessarily sorted help description.  */
  char * sizes_file_arg;	/* Output file for sizes computed from tree.  */
  char * sizes_file_orig;	/* Output file for sizes computed from tree original value given at command line.  */
  const char *sizes_file_help; /* Output file for sizes computed from tree help description.  */
  char * tree_file_arg;	/* Filename containing the tree.  */
  char * tree_file_orig;	/* Filename containing the tree original value given at command line.  */
  const char *tree_file_help; /* Filename containing the tree help description.  */
  float missing_val_arg;	/* The defualt weight for missing edges (default='100').  */
  char * missing_val_orig;	/* The defualt weight for missing edges original value given at command line.  */
  const char *missing_val_help; /* The defualt weight for missing edges help description.  */
  int num_splits_arg;	/* split the new edges file into this number of files.  */
  char * num_splits_orig;	/* split the new edges file into this number of files original value given at command line.  */
  const char *num_splits_help; /* split the new edges file into this number of files help description.  */
  
  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int existing_edges_file_given ;	/* Whether existing-edges-file was given.  */
  int new_edges_file_given ;	/* Whether new-edges-file was given.  */
  int sizes_file_given ;	/* Whether sizes-file was given.  */
  int tree_file_given ;	/* Whether tree-file was given.  */
  int missing_val_given ;	/* Whether missing-val was given.  */
  int num_splits_given ;	/* Whether num-splits was given.  */

} ;

extern const char *gengetopt_args_info_purpose;
extern const char *gengetopt_args_info_usage;
extern const char *gengetopt_args_info_help[];

int cmdline_parser (int argc, char * const *argv,
  struct gengetopt_args_info *args_info);
int cmdline_parser2 (int argc, char * const *argv,
  struct gengetopt_args_info *args_info,
  int override, int initialize, int check_required);
int cmdline_parser_file_save(const char *filename,
  struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

void cmdline_parser_init (struct gengetopt_args_info *args_info);
void cmdline_parser_free (struct gengetopt_args_info *args_info);

int cmdline_parser_required (struct gengetopt_args_info *args_info,
  const char *prog_name);


#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* HASHINGMERGERMAIN_CMDLINE_H */
