# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Initialise boosting with chosen accelerator hardware (x86, AVX, FMA)
#' 
#' @param data Matrix
#' @param stepno Amount of steps
#' @param mode Accelerator mode (0: x86, 1: FMA, 2: AVX)
cpp_filter_base <- function(data, stepno = 20L, mode_ = 2L) {
    invisible(.Call('netboost_filter_base', PACKAGE = 'netboost', data, stepno, mode_))
}

#' @title Boosting cleanup (required to free memory)
#' 
cpp_filter_end <- function() {
    invisible(.Call('netboost_filter_end', PACKAGE = 'netboost'))
}

#' @title Single boosting step
#' 
#' @details Must be initialised before using @see{filter_base}
#' 
#' @param col_y Row in data matrix
cpp_filter_step <- function(col_y) {
    .Call('netboost_rcpp_filter_step', PACKAGE = 'netboost', col_y)
}

#' @title Function to calcutate distance
#' @details
#' Steps:
#'   1. - Sequential preparation of index and partner caches per value in filter
#'   2. - Parallel calculation of the distances with cached vectors
#'
#' @todo Preparation of cache could also be done in parallel
#'
#' @export
#' @param filter Filter matrix
#' @param adjacency Vector
cpp_dist_tom <- function(filter, adjacency) {
    .Call('netboost_dist_tom', PACKAGE = 'netboost', filter, adjacency)
}

#' @title Tree search.
#' @details Constraint: IDs 0 <= x (Integer)
#'
#' @param netboost_forest Input-matrix (4 columns, ids in colum 0,1,3)
#'  export  (NO export here, wrapper in R required)
#'
cpp_tree_search <- function(netboost_forest) {
    .Call('netboost_tree_search', PACKAGE = 'netboost', netboost_forest)
}

